# site setting
title: optin
baseurl: /unbounce
tagline: Sample Optin Form.
description: Fill in your email details and get the five Steps to obtaining A1 credit.
#heading
heading: Your Primary headline
sub-heading: your secondary headline
#book-heading
book-heading: A pratical Guide
book-main-heading: Conversion Design
#middle-content
intro-para: Add some descriptive content here to illustrate what the ebook is about and the benefits (what you'll learn) attributed to reading it. You may want to mention how many pages it is to set expectations.
point-heading: Insert Chapter Titles
point-content: Describe the content of each chapter and what you'll learn from it. Key takeaways.
two-point-heading: Another Chapter Title
two-point-content: Describe the content of each chapter and what you'll learn from it. Key takeaways.
three-point-heading: Another Chapter Title
three-point-content: Describe the content of each chapter and what you'll learn from it. Key takeaways.
#contact
contact-title: Credit Repair Consultant
contact-desc: George is great with clients and explains the loan process to them in perfect detail. I highly recommend him to anyone needing a loan to buy a home or to refinance. 
contact-num: 6478794709
#build setting
markdown: kramdown
  
exclude: ['README.md']
permalink: pretty #to remove .html

#sociallinks
facebook_username: Hatkit-Credit-Repair-1887916628195003
twitter_username: hatkit83   
instagram_username: crigroups
youtube_username: crigroups
google-plus_username: u/0/109075708523313177474
gems:
  - jekyll-seo-tag
  - jekyll-sitemap
